---
-
  gather_facts: false
  vars_files:
    - '{{file}}'
  hosts: "{{tenant.cloudIP}}"
  tasks:
    - name: Create site namespace
      command: "ip netns add {{tenant.tenant_name}}_{{tenant.site}}"
      ignore_errors: true

    # Create veth pair
    - name: Create veth pair
      command: "ip link add {{tenant.tenant_name}}{{tenant.site}}_sp type veth peer name {{tenant.tenant_name}}{{tenant.site}}_ps"
      ignore_errors: true

    # Add vethpair interface to namespace
    - name: Add vethpair interface to SiteNS
      command: "sudo ip link set {{tenant.tenant_name}}{{tenant.site}}_sp netns {{tenant.tenant_name}}_{{tenant.site}}"
      ignore_errors: true

    # Assign ip to vethpair interface inside transit vpc namespace
    - name: Add ip address to veth pair inside SiteNS
      command: "sudo ip netns exec {{tenant.tenant_name}}_{{tenant.site}} ip addr add {{tenant.tenant_id}}.{{tenant.site_id}}.{{tenant.site_id}}.1/24 dev {{tenant.tenant_name}}{{tenant.site}}_sp"
      ignore_errors: true

    # Assign ip to vethpair interface inside host
    - name: Add ip address to veth pair inside hypervisor
      command: "sudo ip addr add {{tenant.tenant_id}}.{{tenant.site_id}}.{{tenant.site_id}}.2/24 dev {{tenant.tenant_name}}{{tenant.site}}_ps"
      ignore_errors: true

    # Set link as up
    - name: Set veth interface in the SiteNS up
      command: "sudo ip netns exec {{tenant.tenant_name}}_{{tenant.site}} ip link set {{tenant.tenant_name}}{{tenant.site}}_sp up"
      ignore_errors: true

    # Set link as up
    - name: Set veth interface in hypervisor up
      command: "sudo ip link set {{tenant.tenant_name}}{{tenant.site}}_ps up"
      ignore_errors: true

    # Add default route to be of host
    - name: Add default route in SiteNS
      command: "sudo ip netns exec {{tenant.tenant_name}}_{{tenant.site}} ip route add default via {{tenant.tenant_id}}.{{tenant.site_id}}.{{tenant.site_id}}.2"
      ignore_errors: true
