---
- gather_facts: false
  hosts: hypervisor
  vars:
    - "{{file}}"
  tasks:
    - name: Set the bridge down
      command: "sudo ip link set t{{ site.tenantID }}s{{ site.siteID }}v{{ item.vmID }}br down"
      with_items: "{{site.vms}}"

    - name: Delete the bridge
      command: "sudo brctl delbr t{{ site.tenantID }}s{{ site.siteID }}v{{ item.vmID }}br"
      with_items: "{{site.vms}}"

    - name: Destroy the network
      virt_net:
        command: destroy
        name: "{{ site.siteNS }}{{ item.vmName }}_CENSnet"
      with_items: "{{site.vms}}"
      
    - name: Undefine the network
      virt_net:
        command: undefine
        name: "{{ site.siteNS }}{{ item.vmName }}_CENSnet"
      with_items: "{{site.vms}}"
