---
-
  gather_facts: false
  vars_files:
    - '{{file}}'
  hosts: "{{tenant.cloudIP}}"
  vars:
    imageLocation: /var/lib/libvirt/images/skundalVM1.img
    vmDiskLocation: /var/lib/libvirt/images
  tasks:

    - name: destroy VMS
      command: "sudo virsh destroy {{item.name}}"
      with_items: "{{router}}"
      ignore_errors: true

    - name: destroy Undefine
      command: "sudo virsh undefine {{item.name}}"
      with_items: "{{router}}"
      ignore_errors: true


    - name: set the bridge veth interface down
      command: "sudo ip link set dev {{item.name}}-veth2 down"
      with_items: "{{router}}"
      ignore_errors: true

    - name: Delete the interface
      command: "sudo ip del dev {{item.name}}-veth2"
      with_items: "{{router}}"
      ignore_errors: true

    - name: Set the bridge down
      command: "sudo ip link set dev {{item.name}}-br down"
      with_items: "{{router}}"
      ignore_errors: true


    - name: Delete bridge connected to the network
      command: "sudo brctl delbr {{item.name}}-br"
      with_items: "{{router}}"
      ignore_errors: true

    - name: Delete Virtual Network
      command: "sudo virsh net-destroy {{item.name}}-net"
      with_items: "{{router}}"
      ignore_errors: true

    - name: Undefine Virtual Network
      command: "sudo virsh net-undefine {{item.name}}-net"
      with_items: "{{router}}"
      ignore_errors: true
