---
- name: Get IP Table Rules
  vars_files:
    - hostVars.yaml
  hosts: "{{host}}"
  become: yes
  become_user: root
  tasks:
    - name: Get IP Table Rules With Line Number
      command: iptables -L --line-number
      register: output

    - set_fact:
        cacheable: yes
        output: "{{output.stdout}}"

