---
CE:
  tenant_id: 50
  tenant_name: t50
  site: ns2
  site_id: 2
  hypervisorType: primary
  delete_container: 'y'
  container:
    - image: hw4
      id: 1
      delete_link: 'y'
      PE: [1, 2]
