---
tenant:
        tenant_id: 50
        tenant_name: 't50'
        change_site: 'y'
        change_net: 'y'
        change_container: 'y'
        hypervisorType: 'secondary'
        site: 'ns3'
        site_id: 3
        site_ip_int: '3.1.3.1'
        site_ip_ext: '3.1.3.2'
        networks: [1]
        PE: [3]
router:
   - container_id: 1
     change_link: 'n'
     networks: [1]
     image: hw4
