--- 
- 
  gather_facts: false
  hosts: localhost
  tasks: 
    - 
      copy: 
        dest: "{{ vmDiskLocation }}/{{ item.vmName }}.img"
        src: "{{ imageLocation }}"
      name: "Copying template file for {{ item.vmName }}"
      with_items: "{{ vms }}"
    - 
      name: "Create the vm"
      virt: 
        command: define
        name: "{{ item.vmName }}"
        xml: "{{ lookup( \"template\", \"templates/controllerTemplate.xml.j2\" ) }}"
      with_items: "{{ vms }}"
    - 
      name: "Start the vm"
      virt: 
        name: "{{ item.vmName }}"
        state: running
      with_items: "{{ vms }}"
  vars: 
    imageLocation: /var/lib/libvirt/images/skundalVM1.img
    vmDiskLocation: /var/lib/libvirt/images
  vars_files: 
    - controllerNetConfVar.yaml


