--- 
- 
  gather_facts: false
  hosts: localhost
  tasks:
    - debug:
        msg: "{{ file }}"
    - 
      name: "Define the controller network"
      virt_net: 
        command: define
        name: "{{ tenantInfo.tenantID }}_controller_net"
        xml: "{{ lookup(\"template\", \"templates/controllerNetworkTemplate.xml.j2\"  ) }}"
    - 
      name: "Start the controller Network"
      virt_net: 
        command: create
        name: "{{ tenantInfo.tenantID }}_controller_net"
        state: active
    - 
      name: "Create the VXLAN interface"
      shell: "ip link add name {{ tenantInfo.tenantID }}-vxlan type vxlan id {{ tenantInfo.tenantID }} dev ens5 remote {{ tenantInfo.remoteIP }} dstport 4789"
    - 
      name: "Bring up the VXLAN interface"
      shell: "ip link set {{ tenantInfo.tenantID }}-vxlan up"
    -
      name: "Attach the VxLAN interface to the bridge"
      shell: "brctl addif {{ tenantInfo.tenantID }}-controllerbr {{ tenantInfo.tenantID }}-vxlan" 
    - 
      name: "Create veth pair"
      shell: "ip link add veth_{{ tenantInfo.tenantID }}c2t type veth peer name veth_t2c{{ tenantInfo.tenantID }}"
    - 
      name: "Add one veth to controller switch"
      shell: "brctl addif {{ tenantInfo.tenantID }}-controllerbr veth_{{ tenantInfo.tenantID }}c2t"
    - 
      name: "Add another veth to the namespace"
      shell: "ip link set dev veth_t2c{{ tenantInfo.tenantID }} netns {{ tenantInfo.tenantName }}_transit"
    - 
      name: "Bring up the veth interface @switch"
      shell: "ip link set dev veth_{{ tenantInfo.tenantID }}c2t up"
    - 
      name: "Bring up the veth interface @ns"
      shell: "ip netns exec {{ tenantInfo.tenantName }}_transit ip link set dev veth_t2c{{ tenantInfo.tenantID }} up"
    - 
      name: "Run dhclient in the namespace for this interface"
      shell: "ip netns exec {{ tenantInfo.tenantName }}_transit dhclient veth_t2c{{ tenantInfo.tenantID }}"
  vars_files: 
    - '{{ file }}'

