--- 
- 
  gather_facts: false
  hosts: hypervisor
  tasks: 
  #    - 
  #    copy: 
  #      dest: "{{ vmDiskLocation }}/{{ site.siteNS }}{{ item.vmName }}.img"
  #      src: "{{ imageLocation }}"
  #    name: "Copying VM image template"
  #    with_items: "{{ site.vms }}"
  #    ignore_errors: true
  #  - 
  #    name: "Create the vm"
  #    virt: 
  #      command: define
  #      name: "{{ site.siteNS }}{{ item.vmName }}"
  #      xml: "{{ lookup( \"template\", \"templates/CETemplate.xml.j2\" ) }}"
  #    with_items: "{{ site.vms }}"
  #    ignore_errors: true
  #  - 
  #    name: "Start the vm"
  #    virt: 
  #      name: "{{ site.siteNS }}{{ item.vmName }}"
  #      state: running
  #    with_items: "{{ site.vms }}"
  #    ignore_errors: true
    -
      name: Create a bridge to connect to the hypervisor
      command: "brctl addbr s{{site.siteID}}{{item.vmName}}br"
      with_items: "{{site.vms}}"
      ignore_errors: true
    -
      name: Set the bridge up
      command: "ip link set s{{site.siteID}}{{item.vmName}}br up"
      with_items: "{{site.vms}}"
      ignore_errors: true
    -
      name: Define a network in the hypervisor
      virt_net:
        command: define
        name: "s{{site.siteID}}{{item.vmName}}net"
        xml: "{{ lookup(\"template\", \"templates/CEHypTemplate.xml.j2\"  ) }}" 
      with_items: "{{site.vms}}"
      ignore_errors: true
    -
      name: Start the network
      virt_net:
        command: create
        name: "s{{site.siteID}}{{item.vmName}}net"
        state: active
      with_items: "{{site.vms}}"
      ignore_errors: true
    -
      name: Attach an interface to the CE
      command: "sudo virsh attach-interface --domain {{site.siteNS}}{{item.vmName}} --type network s{{site.siteID}}{{item.vmName}}net --model virtio --config --live"
      with_items: "{{ site.vms }}"
      ignore_errors: true

      # vars: 
      # imageLocation: /var/lib/libvirt/images/skundalVM1.img
      #vmDiskLocation: /var/lib/libvirt/images
  vars_files: 
    - '{{ file }}'

