---
tenant:
        tenant_id: 50
        tenant_name: 't50'
        change_ns: 'y'
        change_net: 'y'
        change_vm: 'y'
        hypervisor: 'primary'
        site: 'ns1'
        site_id: 1
        site_ip_int: '1.2.3.1'
        site_ip_ext: '1.2.3.2'
        networks: ['net1','net2']
router:
   - name: 't50_VM1'
     ip: ['1.1.1.0/24', '1.1.2.0/24']
     networks: ['net1', 'net2']
     mem: 1024
     vcpu: 2
