---
-
  gather_facts: false
  hosts: localhost
  tasks:
    -
      name: "create bridge"
      shell: "sudo brctl addbr {{ bridgeName }}"
    -
      name: "activate bridge interface"
      shell: "sudo ifconfig {{ bridgeName }} up"
    -
      ignore_errors: true
      name: "Define network"
      virt_net:
        command: define
        name: "{{ netName }}"
        xml: "{{ lookup(\"template\", \"templates/CEPETemplate.xml.j2\"  ) }}"
    -
      ignore_errors: true
      name: "Start the network"
      shell: "sudo virsh net-start {{ netName }}"
  vars:
    bridgeName: "{{ bridge }}"
    netName: "{{ network }}"

