---
- name: change default route table
  vars_files:
      - changeRouteVars.yaml
  hosts: "{{ip}}" 
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Remove the default route
      command: "sudo ip route del {{item.source}} via {{item.oldInterface}}"
      with_items: "{{ routing }}"

    - name: Add the default route
      command: "sudo ip route add {{item.source}} via {{item.newInterface}}"
      with_items: "{{ routing }}"
   

