---
PE:
  tenant_id: 50
  tenant_name: t50
  hypervisorType: primary
  change_net: y
  vms:
          - PE_name: PE1
            image: hw4
            id: 1
          - PE_name: PE2
            image: hw4
            id: 2

