--- 
- 
  gather_facts: false
  hosts: localhost
  tasks: 
    - 
      copy: 
        dest: "{{ vmDiskLocation }}/{{ site.siteNS }}{{ item.vmName }}.img"
        src: "{{ imageLocation }}"
      name: "Copying VM image template"
      with_items: "{{ site.vms }}"
      ignore_errors: true
    - 
      name: "Create the vm"
      virt: 
        command: define
        name: "{{ site.siteNS }}{{ item.vmName }}"
        xml: "{{ lookup( \"template\", \"templates/CETemplate.xml.j2\" ) }}"
      with_items: "{{ site.vms }}"
      ignore_errors: true
    - 
      name: "Start the vm"
      virt: 
        name: "{{ site.siteNS }}{{ item.vmName }}"
        state: running
      with_items: "{{ site.vms }}"
      ignore_errors: true
  vars: 
    imageLocation: /var/lib/libvirt/images/skundalVM1.img
    vmDiskLocation: /var/lib/libvirt/images
  vars_files: 
    - '{{ file }}' 

