---
- gather_facts: false
  hosts: hypervisor
  vars:
    - "{{file}}"  
  tasks:
    - name: Destroy the VM
      virt:
        name: "{{item.vmName}}"
        command: destroy
      with_items: "{{site.vms}}"
    - name: Undefine the VM
      virt:
        name: "{{item.vmName}}"
        command: undefine
