---
- hosts: "{{hypervisor}}"
  gather_facts: no
  become_user: root
  tasks:
          - name: Define the network
            virt_net:
                    name: "{{network_name}}"
                    command: define
                    xml: "{{ lookup('template', 'templates/router_template.xml.j2') }}"
          - name: Start the network
            virt_net:
                    name: "{{network_name}}"
                    command: create
