---
- hosts: "{{hypervisor}}"
  gather_facts: no
  become_user: root
  tasks:
    - name: Create a namespace
      command: "sudo ip netns add {{ns_name}}"
      ignore_errors: yes

    - name: Create a vethpair
      command: "sudo ip link add {{ns_name}}1 type veth peer name {{ns_name}}2"
      ignore_errors: yes

    - name: Attach one end of veth pair to the namespace
      command: "sudo ip link set {{ns_name}}1 netns {{ns_name}}"
      ignore_errors: yes

    - name: Set the veth interface inside the namespace up
      command: "sudo ip netns exec {{ns_name}} ip link set dev {{ns_name}}1 up"
      ignore_errors: yes

    - name: Set the veth interface inside the hypervisor up
      command: "sudo ip link set dev {{ns_name}}2 up"
      ignore_errors: yes

    - name: Assign IP to the veth interface inside the namespace
      command: "sudo ip netns exec {{ns_name}} ip addr add {{hypervisorIP}} dev {{ns_name}}1"
      ignore_errors: yes

    - name: Assign IP to the veth interface inside the hypervisor
      command: "sudo ip addr add {{transitIP}} dev {{ns_name}}2"
      ignore_errors: yes
