---
-
  gather_facts: false
  hosts: '{{ hypervisor }}'
  tasks:
    -
      name: Turn veth1 down 
      shell: 'ip link set dev {{ veth1 }} down'
      become: yes
      ignore_errors: yes

    -
      name: Delete veth1
      shell: 'ip link del dev {{ veth1 }}'
      become: yes
      ignore_errors: yes

