---
- hosts: "{{hypervisor}}"
  gather_facts: no
  become_user: root
  tasks:
    - name: Destroy the network
      virt_net: 
        name: "{{network_name}}"
        command: destroy
      ignore_errors: yes

    - name: Undefine the network
      virt_net:
        name: "{{network_name}}"
        command: undefine
      ignore_errors: yes

    - name: Delete vxlan interface
      shell: 'ip link del dev {{ vxlan_name }}-vxlan'
      become: yes
      when: option == 'delete_vxlan'
      ignore_errors: yes
