--- 
tenantInfo: 
  hypervisorType: "primary"
  controllerNet: "Y"
  tenantID: 20
  tenantName: t20
  remoteIP: "192.168.124.107"
  containers: 
    - 
      cName: t20controller1
      cID: 1
      image: controller_sd

  



