--- 
PE: 
  change_net: "y"
  containers: 
    - 
      PE_name: PE1
      id: 1
      image: edge_sd
    - 
      PE_name: PE2
      id: 2
      image: edge_sd
  hypervisorType: primary
  tenant_id: 10
  tenant_name: t10
